import { Product } from '@/types';

/** Shared mock catalog — URLs verified for Next/image + bakery use */
export const MOCK_PRODUCTS: Product[] = [
    {
        product_id: '1',
        name: 'Artisanal Meat Pie',
        description:
            'Our signature flaky pastry filled with seasoned minced beef, potatoes, and carrots. A true taste of Lagos.',
        short_description: 'Golden flaky crust with savory beef filling.',
        price: 1500,
        category: 'Meat Pies',
        image_url:
            'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800',
        image_gallery: [
            'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
        ],
        stock_quantity: 50,
        is_available: true,
        is_featured: true,
        rating: 4.8,
        review_count: 24,
        ingredients: 'Beef, Flour, Butter, Potatoes, Carrots, Onions, Spices',
        shelf_life: '2-3 days refrigerated',
        created_at: '2024-01-01T12:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        product_id: '2',
        name: 'Premium Agege Bread',
        description:
            'Extra soft, stretchy, and slightly sweet traditional Nigerian white bread. Baked fresh every morning.',
        short_description: 'Traditional soft & stretchy Nigerian white bread.',
        price: 800,
        category: 'Agege Bread',
        image_url:
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
        stock_quantity: 100,
        is_available: true,
        is_featured: true,
        rating: 4.9,
        review_count: 56,
        created_at: '2024-01-02T12:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        product_id: '3',
        name: 'Red Velvet Celebration Cake',
        description: 'Rich cocoa-infused red velvet sponge with layers of silky cream cheese frosting.',
        short_description: 'Rich red velvet with premium cream cheese frosting.',
        price: 15000,
        category: 'Cakes',
        image_url:
            'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800',
        image_gallery: [
            'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&q=80&w=800',
        ],
        stock_quantity: 10,
        is_available: true,
        is_featured: true,
        rating: 4.7,
        review_count: 15,
        created_at: '2024-01-03T12:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        product_id: '4',
        name: 'Spicy Fish Pie',
        description: 'Crispy pastry filled with flaked white fish, peppers, and traditional spices.',
        short_description: 'Savory fish filling with a hint of Nigerian spice.',
        price: 1200,
        category: 'Fish Pies',
        image_url:
            'https://images.unsplash.com/photo-1509315703195-529879416a7d?auto=format&fit=crop&q=80&w=800',
        stock_quantity: 40,
        is_available: true,
        is_featured: true,
        rating: 4.5,
        review_count: 12,
        created_at: '2024-01-04T12:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        product_id: '5',
        name: 'Gourmet Chin Chin',
        description: 'Crunchy, bite-sized fried dough snacks flavored with nutmeg and vanilla.',
        short_description: 'Classic crunchy Nigerian snack with nutmeg notes.',
        price: 2500,
        category: 'Snacks',
        image_url:
            'https://images.unsplash.com/photo-1511911063855-2bf39afa5b2e?auto=format&fit=crop&q=80&w=800',
        stock_quantity: 30,
        is_available: true,
        is_featured: true,
        rating: 4.8,
        review_count: 31,
        created_at: '2024-01-05T12:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        product_id: '6',
        name: 'Golden Puff Puff',
        description: 'Sweet, deep-fried dough balls. Soft, airy, and dangerously addictive.',
        short_description: 'Soft, airy fried dough balls - a street food favorite.',
        price: 1000,
        category: 'Snacks',
        image_url:
            'https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?auto=format&fit=crop&q=80&w=800',
        stock_quantity: 60,
        is_available: true,
        is_featured: false,
        rating: 4.9,
        review_count: 120,
        created_at: '2024-01-06T12:00:00Z',
        updated_at: new Date().toISOString(),
    },
];
